% Define the float values for each island
floatValues = struct(...
    'TX_CedarLakes', 0.94, ...
    'AL_Dauphin', 1.02, ...
    'FL_Shell', 1.33, ...
    'MA_Plum', 2.77, ...
    'NC_BaldHead', 2.05, ...
    'NC_Masonboro', 1.9, ...
    'NC_Portsmouth', 1.6, ...
    'TX_Follets', 0.88, ...
    'TX_Hog', 0.99, ...
    'TX_MatagordaPeninsula', 0.88, ...
    'VA_Assateague', 2.2, ...
    'VA', 1.7, ...
    'TX_GV', 0.88, ...
    'TX_CC', 1.05, ...
    'OR_SB', 3.68, ...
    'CA', 2.59, ...
    'FL', 1.33, ...
    'FL_SP', 1.05, ...
    'AUS_NSW', 2.8, ...
    'HI', 2.48, ...
    'IT', 3.26, ...
    'AK', 3.55, ...
    'MA', 2.77 ...
);

% Assuming islandNames is defined and has the correct format
% and assuming 'Ref' data is already available in the workspace
Beach = struct();
for i = 1:length(islandNames)
    fileName = islandNames{i};
    if isfield(floatValues, fileName) && isfield(Ref, fileName)
        % Retrieve the float value and the Ref value
        floatValue = getfield(floatValues, fileName);
        refValue = getfield(Ref, fileName);
        % Add them together and assign to Beach struct
        Beach.(fileName) = floatValue + refValue;
    else
        fprintf('Missing data for %s\n', fileName);
    end
end

clear fileName i floatValue refValue

% Save the Beach struct
save('BeachElevations.mat', 'Beach');
