sz = 12;
lwd = 1.5;

% Specify the position of each text label based on the given values
textPositions = struct(...
    'TX_CedarLakes', [0.5, 1.2], ...
    'AL_Dauphin', [0.3, 0.9], ...
    'FL_Shell', [0.4, 1.1], ...
    'MA_Plum', [1.7, 1.6], ...
    'NC_BaldHead', [0.7, 1.4], ...
    'NC_Masonboro', [0.7, 1.4], ...
    'NC_Portsmouth', [0.7, 1.4], ...
    'TX_Follets', [0.4, 0.9], ...
    'TX_Hog', [0.4, 0.9], ...
    'TX_MatagordaPeninsula', [0.4, 0.9], ...
    'VA_Assateague', [0.9, 1.1], ...
    'VA', [0.9, 1.1], ...
    'TX_GV', [0.4, 0.9], ...
    'TX_CC', [0.4, 1.3], ...
    'OR_SB', [1.4, 2.6], ...
    'CA', [0.9, 1.0], ...
    'FL', [0.7, 0.8], ...
    'FL_SP', [0.6, 1.0], ...
    'AUS_NSW', [0.8, 1.3], ...
    'HI', [0.5, 1.7], ...
    'IT', [0.5, 0.4], ...
    'AK', [1.8, 2.2], ...
    'MA', [1.7, 1.6] ...
);

figure
hold on
for i = 1:numel(islandNames)
    islandName = islandNames{i};
    displayName = strrep(islandName, '_', '\_'); % Convert underscores for LaTeX interpreter
    if isfield(TA, islandName) && isfield(Hs, islandName) && isfield(HsSD, islandName)
        errorbar(TA.(islandName), Hs.(islandName), HsSD.(islandName), HsSD.(islandName), ...
            '.', 'color', Colors.(islandName), 'MarkerSize', sz, 'LineWidth', lwd);
        plot(TA.(islandName), Hs.(islandName), 'o', 'MarkerEdgeColor', 'k', 'MarkerFaceColor', Colors.(islandName), ...
            'MarkerSize', sz, 'LineWidth', lwd);
        if isfield(textPositions, islandName)
            textPos = textPositions.(islandName);
            text(textPos(1), textPos(2), displayName, 'FontSize', sz, 'Color', Colors.(islandName), 'Interpreter', 'latex');
        else
            text(TA.(islandName), Hs.(islandName), displayName, 'FontSize', sz, 'Color', Colors.(islandName), 'Interpreter', 'latex');
        end
    end
end

axis([0 2 0 4])
xline(1, '--', 'Color', 'k', 'LineWidth', 1.5)
xlabel('Tidal Amplitude $A_{t}$ (m)', 'Interpreter', 'latex', 'FontSize', 20)
ylabel('Mean significant wave height $H_{s}$ (m)', 'Interpreter', 'latex', 'FontSize', 20)
set(gca, 'FontSize', 20)
set(gcf, 'Position', get(0, 'Screensize'));

hold off
