

% Predefined attributes
Names = struct(...
    'TX_CedarLakes', 'TX - CedarLakes', ...
    'AL_Dauphin', 'AL - Dauphin', ...
    'FL_Shell', 'FL - Shell', ...
    'MA_Plum', 'MA - Plum', ...
    'NC_BaldHead', 'NC - BaldHead', ...
    'NC_Masonboro', 'NC - Masonboro', ...
    'NC_Portsmouth', 'NC - Portsmouth', ...
    'TX_Follets', 'TX - Follets', ...
    'TX_Hog', 'TX - Hog', ...
    'TX_MatagordaPeninsula', 'TX - MatagordaPeninsula', ...
    'VA_Assateague', 'VA - Assateague', ...
    'VA', 'VA', ...
    'TX_GV', 'TX - GV', ...
    'TX_CC', 'TX - CC', ...
    'OR_SB', 'OR - SB', ...
    'CA', 'CA', ...
    'FL', 'FL', ...
    'FL_SP', 'FL - SP', ...
    'AUS_NSW', 'AUS - NSW', ...
    'HI', 'HI', ...
    'IT', 'IT', ...
    'AK', 'AK', ...
    'MA', 'MA' ...
);


% Adjusting the Colors structure
Colors = struct(...
    'AL_Dauphin', [1, 1, 0], ...
    'FL_Shell', [1, 0, 1], ...
    'MA_Plum', [0, 1, 1], ...
    'NC_BaldHead', [0.6350, 0.0780, 0.1840], ...
    'NC_Masonboro', [0, 0, 1], ...
    'NC_Portsmouth', [0.9290, 0.6940, 0.1250], ...
    'TX_Follets', [0, 0.4470, 0.7410], ...
    'TX_Hog', [0, 0.5, 0], ...
    'TX_MatagordaPeninsula', [1, 0, 0], ...
    'VA_Assateague', [0, 1, 0], ...
    'TX_GV', [0.62, 0.04, 0.86], ...
    'TX_CC', [0.98, 0.5, 0.45], ...
    'OR_SB', [0.05, 0.7, 0.62], ...
    'CA', [0.98, 0.91, 0.62], ...
    'FL', [0.84, 0.86, 0.87], ...
    'FL_SP', [0, 0, 0], ...
    'AUS_NSW', [1, 0.5, 0.5], ...
    'HI', [0, 0, 0], ...
    'IT', [0.6, 0.2, 0], ...
    'AK', [0.5, 0.5, 0], ...
    'MA', [0.6, 0.6, 0.6], ...
    'VA', [0.7, 0.6, 0.6], ...
    'TX_CedarLakes', [0, 0, 0] ...
);

% Adjusting the MSLToNAVD88 structure
MSLToNAVD88 = struct(...
    'AL_Dauphin', -0.016, ...
    'FL_Shell', -0.041, ...
    'MA_Plum', 0.092, ...
    'NC_BaldHead', 0.112, ...
    'NC_Masonboro', 0.112, ...
    'NC_Portsmouth', 0.112, ...
    'TX_Follets', -0.158, ...
    'TX_Hog', -0.158, ...
    'TX_MatagordaPeninsula', -0.158, ...
    'VA_Assateague', 0.106, ...
    'TX_GV', -0.158, ...
    'TX_CC', -0.131, ...
    'OR_SB', -1.124, ...
    'CA', -0.905, ...
    'FL', 0.288, ...
    'FL_SP', 0.096, ...
    'AUS_NSW', NaN, ...
    'HI', NaN, ...
    'IT', NaN, ...
    'AK', NaN, ...
    'MA', 0.092, ...
    'TX_CedarLakes', -0.158 ...
);


% Initialize structures for dynamically loaded attributes
Slopes = struct();
Ref = struct();
Lambda = struct();
Lambda2 = struct();
Mu = struct();
Threshold = struct();

% Load additional data from .mat files and assign them
for i = 1:length(islandNames)
    fileName = islandNames{i};
    matData = evalin( 'base', fileName); % Directly access variable by name        

    % Direct assignments from .mat data, wrapped in try-catch in case of missing fields
    Slopes.(fileName) = rmmissing(matData.Slope);
    Ref.(fileName) = rmmissing(matData.Reference);
    
    Lambda.(fileName) = rmmissing(matData.Lambda)*365;
    Lambda2.(fileName) = rmmissing(matData.Lambda)*365;

    Mu.(fileName) = rmmissing(matData.Mu);


    Threshold.(fileName) = rmmissing(matData.Threshold);
    

end

% Save the structures to .mat files
save('Names.mat', 'Names');
save('Colors.mat', 'Colors');
save('MSLToNAVD88.mat', 'MSLToNAVD88');
save('Slopes.mat', 'Slopes');
save('Ref.mat', 'Ref');
save('Lambda.mat', 'Lambda');
save('Lambda2.mat', 'Lambda2');
save('Mu.mat', 'Mu');
save('Threshold.mat', 'Threshold');
clear muField thresholdField i fileName fields matData